export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const SUBTRACT_QUANTITY = "SUBTRACT_QUANTITY"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const FILTER_LOW_TO_HIGH = "FILTER_LOW_TO_HIGH"
export const FILTER_HIGH_TO_LOW = "FILTER_HIGH_TO_LOW"
export const FILTER_RECOMMENDED = "FILTER_RECOMMENDED"
export const EMPTY_CART = "EMPTY_CART"


